--- 
abstract: The literal unread
author: 
  - Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: dan
no_index: 
  directory: 
    - inc
    - t
requires: 
  Encode: 0
  perl: 5.9.5
version: 0.551.2
